const allItems = [
  {
    id: 1,
    name: "Coke",
    type: "drink",
    imageUrl: "https://example.com/images/coke.jpg",
    timestamp: 20,
  },
  {
    id: 2,
    name: "Orange Juice",
    type: "drink",
    imageUrl: "https://example.com/images/orange_juice.jpg",
    timestamp: 20,
  },
  {
    id: 3,
    name: "Water",
    type: "drink",
    imageUrl: "https://example.com/images/water.jpg",
    timestamp: 20,
  },
  {
    id: 4,
    name: "Tea",
    type: "drink",
    imageUrl: "https://example.com/images/tea.jpg",
    timestamp: 20,
  },
  {
    id: 5,
    name: "Coffee",
    type: "drink",
    imageUrl: "https://example.com/images/coffee.jpg",
    timestamp: 20,
  },
  {
    id: 6,
    name: "Almond milk",
    type: "drink",
    imageUrl: "https://example.com/images/almond_milk.jpg",
    timestamp: 20,
  },
  {
    id: 7,
    name: "Oat milk",
    type: "drink",
    imageUrl: "https://example.com/images/oat_milk.jpg",
    timestamp: 20,
  },
  {
    id: 8,
    name: "Carrot",
    type: "vegetable",
    imageUrl: "https://example.com/images/carrot.jpg",
    timestamp: 20,
  },
  {
    id: 9,
    name: "Lettuce",
    type: "vegetable",
    imageUrl: "https://example.com/images/lettuce.jpg",
    timestamp: 20,
  },
  {
    id: 10,
    name: "Tomato",
    type: "vegetable",
    imageUrl: "https://example.com/images/tomato.jpg",
    timestamp: 20,
  },
  {
    id: 11,
    name: "Pepper",
    type: "vegetable",
    imageUrl: "https://example.com/images/pepper.jpg",
    timestamp: 20,
  },
  {
    id: 12,
    name: "Cucumber",
    type: "vegetable",
    imageUrl: "https://example.com/images/cucumber.jpg",
    timestamp: 20,
  },
  {
    id: 13,
    name: "Rucola",
    type: "vegetable",
    imageUrl: "https://example.com/images/rucola.jpg",
    timestamp: 20,
  },
  {
    id: 14,
    name: "Apple",
    type: "fruit",
    imageUrl: "https://example.com/images/apple.jpg",
    timestamp: 20,
  },
  {
    id: 15,
    name: "Banana",
    type: "fruit",
    imageUrl: "https://example.com/images/banana.jpg",
    timestamp: 20,
  },
  {
    id: 16,
    name: "Pear",
    type: "fruit",
    imageUrl: "https://example.com/images/pear.jpg",
    timestamp: 20,
  },
  {
    id: 17,
    name: "Kiwi",
    type: "fruit",
    imageUrl: "https://example.com/images/kiwi.jpg",
    timestamp: 20,
  },
  {
    id: 18,
    name: "Watermelon",
    type: "fruit",
    imageUrl: "https://example.com/images/watermelon.jpg",
    timestamp: 20,
  },
  {
    id: 19,
    name: "Durian",
    type: "fruit",
    imageUrl: "https://example.com/images/durian.jpg",
    timestamp: 20,
  },
  {
    id: 20,
    name: "Dragon Fruit",
    type: "fruit",
    imageUrl: "https://example.com/images/dragon_fruit.jpg",
    timestamp: 20,
  },
  {
    id: 21,
    name: "Fish can",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/fish_can.jpg",
    timestamp: 20,
  },
  {
    id: 22,
    name: "Cat food",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/cat_food.jpg",
    timestamp: 20,
  },
  {
    id: 23,
    name: "Apple puree",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/apple_puree.jpg",
    timestamp: 20,
  },
  {
    id: 24,
    name: "Plums",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/plums.jpg",
    timestamp: 20,
  },
  {
    id: 25,
    name: "capers",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/capers.jpg",
    timestamp: 20,
  },
  {
    id: 26,
    name: "Ketchup",
    type: "sauce",
    imageUrl: "https://example.com/images/ketchup.jpg",
    timestamp: 20,
  },
  {
    id: 27,
    name: "Mayonnaise",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/mayo.jpg",
    timestamp: 20,
  },
  {
    id: 28,
    name: "Mustard",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/mustard.jpg",
    timestamp: 20,
  },
  {
    id: 29,
    name: "Soy Sauce",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/soy_sauce.jpg",
    timestamp: 20,
  },
  {
    id: 30,
    name: "Barbecue Sauce",
    type: "sauceAndCanned",
    imageUrl: "https://example.com/images/barbecue_sauce.jpg",
    timestamp: 20,
  },
  {
    id: 31,
    name: "Salmon",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/salmon.jpg",
    timestamp: 15,
  },
  {
    id: 32,
    name: "Sushi",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/sushi.jpg",
    timestamp: 15,
  },
  {
    id: 33,
    name: "Chicken breast",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/chicken_breast.jpg",
    timestamp: 30,
  },
  {
    id: 34,
    name: "Bacon",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/bacon.jpg",
    timestamp: 30,
  },
  {
    id: 35,
    name: "Sausage slices",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/sausage_slices.jpg",
    timestamp: 30,
  },
  {
    id: 36,
    name: "Sausages",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/sausages.jpg",
    timestamp: 30,
  },
  {
    id: 37,
    name: "Milk",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/milk.jpg",
    timestamp: 15,
  },
  {
    id: 38,
    name: "Cheese",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/cheese.jpg",
    timestamp: 15,
  },
  {
    id: 39,
    name: "Yogurt",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/yogurt.jpg",
    timestamp: 15,
  },
  {
    id: 40,
    name: "Butter",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/butter.jpg",
    timestamp: 15,
  },
  {
    id: 41,
    name: "Cream",
    type: "fishMeatDairy",
    imageUrl: "https://example.com/images/cream.jpg",
    timestamp: 15,
  },
  {
    id: 42,
    name: "Carbonara",
    type: "ready",
    imageUrl: "https://example.com/images/carbonara.jpg",
    timestamp: 15,
  },
  {
    id: 43,
    name: "Gratin",
    type: "ready",
    imageUrl: "https://example.com/images/gratin.jpg",
    timestamp: 15,
  },
  {
    id: 44,
    name: "Kebab",
    type: "ready",
    imageUrl: "https://example.com/images/kebab.jpg",
    timestamp: 15,
  },
  {
    id: 45,
    name: "Soup",
    type: "ready",
    imageUrl: "https://example.com/images/soup.jpg",
    timestamp: 15,
  },
  {
    id: 46,
    name: "Sandwich",
    type: "ready",
    imageUrl: "https://example.com/images/sandwich.jpg",
    timestamp: 15,
  },
  {
    id: 47,
    name: "Omelette",
    type: "ready",
    imageUrl: "https://example.com/images/omelette.jpg",
    timestamp: 15,
  },
  {
    id: 48,
    name: "Chicken Eggs",
    type: "egg",
    imageUrl: "https://example.com/images/chicken_eggs.jpg",
    timestamp: 15,
  },
  {
    id: 49,
    name: "Quail Eggs",
    type: "egg",
    imageUrl: "https://example.com/images/quail_eggs.jpg",
    timestamp: 15,
  },
  {
    id: 50,
    name: "Duck Eggs",
    type: "egg",
    imageUrl: "https://example.com/images/duck_eggs.jpg",
    timestamp: 15,
  },
  {
    id: 51,
    name: "Goose Eggs",
    type: "egg",
    imageUrl: "https://example.com/images/goose_eggs.jpg",
    timestamp: 15,
  },
  {
    id: 52,
    name: "Frozen Pizza",
    type: "frozen",
    imageUrl: "https://example.com/images/frozen_pizza.jpg",
    timestamp: 10,
  },
  {
    id: 53,
    name: "Ice_cream",
    type: "frozen",
    imageUrl: "https://example.com/images/ice.jpg",
    timestamp: 10,
  },
  {
    id: 54,
    name: "Frozen Berries",
    type: "frozen",
    imageUrl: "https://example.com/images/frozen_berries.jpg",
    timestamp: 10,
  },
  {
    id: 55,
    name: "Frozen Chicken Wings",
    type: "frozen",
    imageUrl: "https://example.com/images/chicken_wings.jpg",
    timestamp: 10,
  },
  {
    id: 56,
    name: "Frozen Broccoli",
    type: "frozen",
    imageUrl: "https://example.com/images/broccoli.jpg",
    timestamp: 10,
  },
  {
    id: 57,
    name: "Frozen Burger Patties",
    type: "frozen",
    imageUrl: "https://example.com/images/burger_patties.jpg",
    timestamp: 10,
  },
  {
    id: 58,
    name: "Frozen French fries",
    type: "frozen",
    imageUrl: "https://example.com/images/frozen_french_fries.jpg",
    timestamp: 10,
  },
];

export const getTenRandomItems = () => {
  const shuffledItems = [...allItems].sort(() => Math.random() - 0.5); // Zufällige Reihenfolge
  return shuffledItems.slice(0, 10); // Die ersten 10 Items
};

export default allItems;
